// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Params struct {
	Before *int `json:"before"`
	After  *int `json:"after"`
	Limit  *int `json:"limit"`
}

type UserQuery struct {
	Username *string `json:"username"`
	ID       *string `json:"id"`
}
